### ISSUE TITLE
add and remove channels

### ISSUE THREAD

**Issue by fheeger** [fheeger/dispatch_bot_backend#10]
PATCH update_channels/ with payload {"channels": {<channel_id>: <channel_name>, ...}} <- this also adds channels
PATCH remove_channels/ with payload {"channels": [<channel_id>, ...]}

server ID and category ID will be in url parameters to determine game

**Comment by fheeger** [comment]
Channel names are for displaying only, everything should be handled by ID

**Comment by fheeger** [comment]
Also GET get_channels
returns a list of channels in the game: [<channel_id>, <channel_id>, .... ]
server ID and category ID will be in url parameters to determine game

**Comment by sheitandard** [comment]
done
already implemented list_channel in bot
